### ISSUE TITLE
Disable microsoft telemetry

### ISSUE THREAD

**Issue by jorgemoralespou** [eduk8s/pkgs-theia-ide#3]
Add these properties to package.json in preferences section: https://github.com/eduk8s/pkgs-theia-ide/blob/develop/opt/theia/package.json#L7

```
"telemetry.enableTelemetry": false
"telemetry.enableCrashReporter": false
```

**Comment by jorgemoralespou** [comment]
Or maybe we need to create a file settings.json that we also configure by default with default preferences we want.
https://theia-ide.org/docs/preferences

**Comment by GrahamDumpleton** [comment]
Perhaps not relevant if switch to code-server editor.

**Comment by GrahamDumpleton** [comment]
Going  to close this. Telemetry is disabled for code-server. Not done anything for Theia. Can revisit it later if have to got back to it for some reason.
